import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Serif, Open_Sans } from "next/font/google";
import "./globals.css";
import { Dock } from "@/components/app/Dock";
import { navigationConfig } from "@/config/navigation";

const titleFont = IBM_Plex_Serif({
  variable: "--font-title",
  weight: ["400", "500"],
  subsets: ["latin"],
});

const bodyFont = IBM_Plex_Sans({
  variable: "--font-body",
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${titleFont.variable} ${bodyFont.variable} antialiased`}
    >
      <body className="min-h-screen w-full">
        <main className="pt-16 pb-8 px-4 md:px-8 w-full">{children}</main>
        <div className="fixed bottom-4 left-0 right-0 z-50 pointer-events-none flex justify-center">
          <div className="pointer-events-auto">
            <Dock items={navigationConfig} />
          </div>
        </div>
      </body>
    </html>
  );
}
